name: debug build notification-logger-android

on:
  push:
    branches: [ main ]
  pull_request:	
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v4
    - name: 'Linux info'
      run: lsb_release -a
    - name: 'Updating ubuntu deps'    
      run: sudo apt update --fix-missing && sudo apt upgrade -y
    - name: 'Installing deps'    
      run: sudo apt install -y android-tools-adb android-tools-fastboot openjdk-17-jdk android-sdk
    - name: 'Set default Java to 17'
      run: sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
    - name: 'Set default javac to 17'
      run: sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
    - name: 'Set JAVA_HOME to Java 17'
      run: echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
    - name: 'Update PATH'
      run: echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV
    - name: 'Set ANDROID_HOME'    
      run: echo "ANDROID_HOME=/usr/lib/android-sdk" >> $GITHUB_ENV
    - name: 'Clear conflicting ANDROID_SDK_ROOT'    
      run: |
        unset ANDROID_SDK_ROOT
        echo "ANDROID_SDK_ROOT=" >> $GITHUB_ENV
    - name: 'Set ANDROID_NDK_HOME'    
      run: echo "ANDROID_NDK_HOME=/usr/lib/android-sdk/ndk/25.2.9519653" >> $GITHUB_ENV
    - name: 'Create local.properties for CI'
      run: |
        echo "sdk.dir=/usr/lib/android-sdk" > local.properties
        echo "ndk.dir=/usr/lib/android-sdk/ndk/25.2.9519653" >> local.properties
    - name: 'Download and extract android-cli tools'    
      run: curl https://dl.google.com/android/repository/commandlinetools-linux-9123335_latest.zip --output commandlinetools-linux-9123335_latest.zip && sudo mkdir /usr/lib/android-sdk/cmdline-tools && sudo unzip -o commandlinetools-linux-9123335_latest.zip -d /usr/lib/android-sdk/cmdline-tools
    - name: 'Listing commandlinetools.zip'
      run: unzip -l commandlinetools-linux-9123335_latest.zip
    - name: 'Reload bash'    
      run: . ~/.bashrc
    - name: 'echo'
      run: echo $ANDROID_HOME && echo '-------' && echo $PATH | tr ':' '\n'
    - name: 'Show SDK environment variables'
      run: |
        echo "ANDROID_HOME: $ANDROID_HOME"
        echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
        echo "ANDROID_NDK_HOME: $ANDROID_NDK_HOME"
        echo "Contents of local.properties:"
        cat local.properties
    - name: 'Clearing the clutter'    
      run: rm commandlinetools-linux-9123335_latest.zip
    - name: 'adb version'    
      run: adb version
    - name: 'unzip version'    
      continue-on-error: true
      run: unzip --version
    - name: 'java version'    
      run: java -version
    - name: 'java-compiler version'    
      run: javac -version
    - name: 'sdkmanager version'    
      run: /usr/lib/android-sdk/cmdline-tools/cmdline-tools/bin/sdkmanager --version
    - name: 'install buildtool 34.0.0 and accept license'    
      run: yes | sudo /usr/lib/android-sdk/cmdline-tools/cmdline-tools/bin/sdkmanager "build-tools;34.0.0" "platform-tools" "ndk;25.2.9519653" "cmake;3.22.1"
    - name: 'accept all licenses'    
      run: yes | /usr/lib/android-sdk/cmdline-tools/cmdline-tools/bin/sdkmanager --licenses
    - name: 'transfer ownership (as tools are installed under root, they need to excuted under root) ,'    
      run: sudo chown -R $(whoami) $ANDROID_HOME
    - name: 'Build android project'    
      run: ./gradlew assembleDebug --debug --stacktrace
    - name: 'list build directory'    
      run: ls app/build/outputs/apk/debug/  
    - name: 'store .apk'
      uses: actions/upload-artifact@v4
      with:
        name: apk-debug
        path: app/build/outputs/apk/debug/app-debug.apk
